In [ ]:
# NumPy (short for Numerical Python) is one of the most important libraries in Python for working with numbers, especially when you’re dealing with arrays, matrices, or scientific computations.
# 🔹 What NumPy is (in simple terms)
#
# NumPy gives you a fast, efficient way to:
#
# Store large amounts of numerical data
# Perform math operations on entire datasets at once
# Work with vectors and matrices (like in math or physics)
#
# At its core is the ndarray (n-dimensional array), which is much faster and more powerful than regular Python lists for numerical work.

In [ ]:
#pip : is a Python package that you can use to install Python
# pip list
# pip show pandas
# pip install numpy




In [3]:
import numpy as np # Aliasname


In [5]:
example_list = [
    [1, 5, 3, 7],
    [8, 5, 3, 8],
    [1, 0, 3, 7],
    [1, 5, 3, 7],
    [8, 5, -3, 8]
]
example_array = np.array(example_list)
type(example_array), example_array


(numpy.ndarray,
 array([[ 1,  5,  3,  7],
        [ 8,  5,  3,  8],
        [ 1,  0,  3,  7],
        [ 1,  5,  3,  7],
        [ 8,  5, -3,  8]]))

In [9]:
zero_array = np.zeros((6, 4))   # 4 represents the number of culumn
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(5) #Vector



array([1., 1., 1., 1., 1.])

In [12]:
rand_array = np.random.randint(10, 50, (5,3))
print(rand_array)

[[24 16 43]
 [29 22 43]
 [41 22 29]
 [24 22 22]
 [30 46 42]]


In [13]:
# this is a 3 dimensional tensor, vorstellen mit Höhe, länge und Breite

tensor_3d = np.random.random((2, 3, 4)) #3 dimensional
print(tensor_3d)       #3 roles, each in 2 dimensions - my own understanding

[[[0.7640183  0.47081153 0.03555669 0.27856762]
  [0.22687081 0.09759294 0.37439204 0.09095741]
  [0.89713989 0.46328742 0.78822314 0.04074982]]

 [[0.27107305 0.36819753 0.41346045 0.11545561]
  [0.60275017 0.41985664 0.26586944 0.49267398]
  [0.17162181 0.61657249 0.21783632 0.69150193]]]


In [14]:
array_top = tensor_3d[0]   # this gives the first upper half of the result
print(array_top)

[[0.7640183  0.47081153 0.03555669 0.27856762]
 [0.22687081 0.09759294 0.37439204 0.09095741]
 [0.89713989 0.46328742 0.78822314 0.04074982]]


In [17]:
# numpy also has range

one_to_ten = np.arange(1, 11)
print(type(one_to_ten), one_to_ten)

<class 'numpy.ndarray'> [ 1  2  3  4  5  6  7  8  9 10]


In [18]:
#.shape is not a method but an attribute
array_top.shape, tensor_3d.shape

((3, 4), (2, 3, 4))

In [19]:
array_top_as_vector = array_top.reshape((12, 1))
print(array_top_as_vector)

[[0.7640183 ]
 [0.47081153]
 [0.03555669]
 [0.27856762]
 [0.22687081]
 [0.09759294]
 [0.37439204]
 [0.09095741]
 [0.89713989]
 [0.46328742]
 [0.78822314]
 [0.04074982]]


In [20]:
array_top_as_vector = array_top.reshape((1, 12))
print(array_top_as_vector)

[[0.7640183  0.47081153 0.03555669 0.27856762 0.22687081 0.09759294
  0.37439204 0.09095741 0.89713989 0.46328742 0.78822314 0.04074982]]


In [25]:
array_top_as_vector = array_top.reshape((6, 2))
print(array_top_as_vector)

[[0.7640183  0.47081153]
 [0.03555669 0.27856762]
 [0.22687081 0.09759294]
 [0.37439204 0.09095741]
 [0.89713989 0.46328742]
 [0.78822314 0.04074982]]


In [35]:
# Ü: Eine matrix 4*3 mit Würfelzahl 1-6 erzeugen.
# Dann daraus eine Matrix 3*4 machen.

matrix1 = np.random.randint(1, 7, (4,3))
print(f"matrix1 (4*3): {matrix1}")

print() #this can be used to create space in the result terminal

matrixx2 = matrix1.reshape((3,4))
print(matrixx2)

matrix1 (4*3): [[6 1 5]
 [6 2 3]
 [4 3 6]
 [5 5 1]]

[[6 1 5 6]
 [2 3 4 3]
 [6 5 5 1]]


In [36]:
array_5_5 = np.random.randint(1, 100, (5,6))
print(array_5_5)

[[41 46 52 56  9 70]
 [82 51 76 50 66 50]
 [44 15 37 39 24 26]
 [10 95 16 52 58  4]
 [27 99 77 51 97 30]]


In [38]:
slice1 = array_5_5 [1, 4]
slice1

np.int32(66)

In [40]:
slice1 = array_5_5 [1:3, 2:4]
print(slice1)

[[76 50]
 [37 39]]


In [41]:
slice2 = array_5_5 [1:, :4]
print(slice2)

[[82 51 76 50]
 [44 15 37 39]
 [10 95 16 52]
 [27 99 77 51]]


In [42]:
slice3 = array_5_5 [1:2, 1:]
print(slice3)

[[51 76 50 66 50]]


In [ ]:
# ü: slice4
# 1. index ganz durchlaufen schrittweite 2
# 2. index: Spalten index 2 und 3

In [44]:
slice4 = array_5_5 [::2, 2:4]
print(slice4)

[[52 56]
 [37 39]
 [77 51]]
